x <- seq(-pi,pi,0.1)
plot(x, sin(x),col="dodgerblue2",pch=20)
points(x,cos(x),col="indianred",pch=20)
pdf("~/ccbb_projects/pretty_plot.pdf")
plot(x, sin(x),col="dodgerblue2",pch=20)
points(x,cos(x),col="indianred",pch=20)
dev.off()
# this is to seperate texts 
j = runif(100)
k = runif(100)
pdf("~/ccbb_projects/pretty_plot.pdf")
plot(j,k,col="mediumorchid2",pch=20)
dev.off()
# this is to seperate text 
pdf("~/ccbb_projects/pretty_plot.pdf")
plot(x, sin(x),col="dodgerblue2",pch=20)
points(x,cos(x),col="indianred",pch=20)
plot(j,k,col="mediumorchid2",pch=20)
dev.off()
install.packages("devtools", type = "binary")
install.packages(devtools)
install.packages("devtools")
library("devtools")
library("devtools")

x <- seq(-pi,pi,0.1)
j = runif(100)
k = runif(100)
pdf("~/ccbb_projects/pretty_plot.pdf")
plot(x, sin(x),col="dodgerblue2",pch=20)
points(x,cos(x),col="indianred",pch=20)
plot(j,k,col="mediumorchid2",pch=20)
dev.off()
